export const TEST_FUNCTION = 'TEST_FUNCTION';
export const INITIAL_GIFS = 'INITIAL_GIFS';
export const ADD_GIFS = 'ADD_GIFS';
export const AUTH_USER = 'AUTH_USER';
export const RECIEVE_MESSAGE = 'RECIEVE_MESSAGE';
export const AUTH_FALSE = 'AUTH_FALSE';
export const SET_USER_INFO = 'SET_USER_INFO';
export const HEARTHSTONE_ADD_INFORMATION = 'HEARTHSTONE_ADD_INFORMATION';
